package serialization;
public class Employee implements java.io.Serializable {
	/**
	 *  Autogenerated serialVersionID value
	 */
	private static final long serialVersionUID = 8742216484998701737L;
	private String name;
	private String department;
	private transient int ssn;
	private int id;

	public Employee(String name, String dept, int ssn, int id) {
		this.name = name;
		this.department = dept;
		this.ssn = ssn;
		this.id = id;
	}
	
	public String toString() {
		return "Name: " + name + "\nDepartment: " + department 
				+ "\nSSN: " + ssn + "\nID: " + id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public int getSSN() {
		return ssn;
	}
	public void setSSN(int ssn) {
		this.ssn = ssn;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
   
}
